version: '3.6'
services:
  antarctic:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

  jupyter:
    build:
      context: .
      dockerfile: binder/Dockerfile
      target: builder
    ports:
      - 8888:8888
    volumes:
      - volumes:
          - ./binder/work:/home/jovyan/work