version: '3.6'
services:
  antarctic:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    extra_hosts:
      - quantsrv:192.168.100.15
    #env_file:
    #  - .config

  r:
    image: lobnek/rstudio
    build:
      context: .
      dockerfile: r/Dockerfile
    volumes:
      - /media/j/notebooks:${WORK}
    ports:
      - ${PORT}:8787
    environment:
      - DISABLE_AUTH=true